name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  build:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    # Create artifacts for manual deployment
    - name: Create deployment artifacts
      run: |
        mkdir -p deployment
        cp -r dist deployment/
        cp package.json deployment/
        cp smithery.yaml deployment/
        cp Dockerfile deployment/
        
    # Upload artifacts for manual deployment
    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v2
      with:
        name: deployment-artifacts
        path: deployment/
        
    - name: Deployment instructions
      run: |
        echo "Build completed successfully."
        echo "To deploy to Smithery.ai:"
        echo "1. Download the deployment artifacts"
        echo "2. Go to https://smithery.ai/new"
        echo "3. Connect your GitHub repository"
        echo "4. Follow the deployment instructions in SMITHERY_DEPLOYMENT.md"